spring:
  application:
    name: trading-system
  datasource:
    url: jdbc:mysql://localhost:3306/trading_db?useSSL=false&serverTimezone=America/New_York&allowPublicKeyRetrieval=true
    username: root
    password: 3pigcourse
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
# Set JVM timezone to Eastern Time
spring.jackson.time-zone: America/New_York
logging:
  level:
    org.hibernate: DEBUG